In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns = ["A","B","C"])

df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
df.tail()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
df.head(2)   #gives first 2 rows

   A  B  C
0  1  2  3
1  4  5  6

In [8]:
df.tail(2)  #gives last 2 rows

   A  B  C
1  4  5  6
2  7  8  9

In [ ]:
df.columns   #gets you what are the columns present in that

Index(['A', 'B', 'C'], dtype='object')

In [ ]:
df   #gets you the entire data present

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df.index    #gets you the index values that are present i.e., row numbers

RangeIndex(start=0, stop=3, step=1)

In [19]:
# We can specifically mention the index 

df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns = ["A","B","C"], index = ["a","b","c"])

In [ ]:
df    # we can see that clearly columns are changed to a,b,c

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [22]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df.info()    # gets you the information about the dataset like data types, null or not null, number of entries and all

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes